### ISSUE TITLE
A user should be able to register for an account

### ISSUE THREAD

**Issue by broskoski** [AOzone/median#1]
_attributes:_ `username`, `email`, `birthday`, `gender`, `password`

**Comment by troyth** [comment]
We should use an expanded notion of gender here. Here's a sample list we could use to pull from Fb:

> So, if you don't identify as male or female, then what? Well, Facebook offers 56 options. You can use up to 10 of them on your profile. Fifty-six sounds like a lot, but actually many of them are variations on a theme—"cisgender man" and "cisgender male," as well as "cis man" and "cis male." In terms of broad categories, there about a dozen
> [Source: Slate, "Confused by All the New Facebook Genders? Here's What They Mean."](http://www.slate.com/blogs/lexicon_valley/2014/02/21/gender_facebook_now_has_56_categories_to_choose_from_including_cisgender.html)

Perhaps we can just use these dozen? [Here's a link to the full list](http://www.slate.com/blogs/future_tense/2014/02/13/facebook_custom_gender_options_here_are_all_56_custom_options.html).

**Comment by troyth** [comment]
@broskoski we would like to slow play this: in addition to a straight forward sign up button, we want to have a live "trade now" (or similar) button on the homepage for an unauth'd user. If they click, they go through a guided (tooltip-based) transaction, at the end of which, in order to make the transaction, they are guided to sign up. See the diagram below. The concept is to give first time users a sense of the experience before they have to sign up.
[Edit: pushed to issue #9 ]

**Comment by broskoski** [comment]
@troyth interesting, i think for the scope of this issue, lets keep it just as a basic login. This flow looks like more of an MVP issue, and would be something like "a user should be able to make a test trade before registering for an account".

**Comment by troyth** [comment]
@broskoski, yeah, makes sense. I'll make a separate issue for the MVP milestone

**Comment by troyth** [comment]
@broskoski I think this IA diagram could be useful for v.0.1, but let me know if this should be scoped for later on as well 
![150828_ia_page_3](https://cloud.githubusercontent.com/assets/2113599/9564655/2482aa7a-4e7c-11e5-9e92-2cff3adc6085.png)
